# SITE CONFIGURATION
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://caroleetpierre" # the base hostname & protocol for your site

# THEME-SPECIFIC CONFIGURATION
theme_settings:
  # Meta
  title: Carole & Pierre
  avatar: 
  gravatar: # Email MD5 hash
  description: "A website with blog posts and pages" # used by search engines

  # Header and footer text
  header_text: >
     <p class="call-out-title">Carole &amp; Pierre</p> 
     <p class="call-out-subtitle">22 Juillet 2017</p>
  header_text_en: > 
    <p class="call-out-title">Carole &amp; Pierre</p> 
    <p class="call-out-subtitle">22 July 2017</p> 
  header_text_feature_image: img/banner.gif
  footer_text: >
   Nous contacter : contact@caroleetpierre.fr<br/><br/><a href="/apropos/">À propos de ce site</a>
  footer_text_en: >
     Contact us: contact@caroleetpierre.fr<br/><br/><a href="/apropos/">About this website</a>
  # Icons
  rss: false
  email_address: # Full email address, e.g. "sam@example.com"
  behance:
  bitbucket:
  dribbble:
  facebook:
  flickr:
  github:
  google_plus:
  instagram:
  linkedin:  # Full URL
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:  # Full URL
  steam:
  tumblr:
  twitter:
  wordpress:
  youtube:

  # Scripts
  google_analytics: # Tracking ID, e.g. "UA-000000-01"
  disqus_shortname:
  muut_community_name: # From muut.com settings, e.g. "muttcommunityname"
  katex: true # Enable if using math markup

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next: "Next"
  str_prev: "Prev"
  str_continue_reading: "Continue reading"

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"

  # Post navigation
  post_navigation: false

# PAGINATION
paginate: 5
paginate_path: "blog/page:num"

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
gems: [jekyll-paginate]
